<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>adb84b59-5cd8-424f-a08c-c7e134300ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close-fixedban']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;adplus-dvertising&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd00d26e-62b3-43ca-a182-e7b6e7a71119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ad.plus/adplus-advertising.svg</value>
      <webElementGuid>a386d76e-d168-4a08-8417-eb5c22a3ea8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>adplus-dvertising</value>
      <webElementGuid>ef51b8af-698f-42ad-9c66-b1b76f3594ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ad.Plus Advertising</value>
      <webElementGuid>62b6bafd-2321-4d4f-8ab8-e055c3824d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)/img[1]</value>
      <webElementGuid>e7a0d420-1f47-4b22-9061-953c85ac483a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']/img</value>
      <webElementGuid>94951c42-5246-4473-b97e-6082d6b79457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='adplus-dvertising']</value>
      <webElementGuid>119dd25b-1133-4efb-8dcc-1cd053ec0e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>deb55abb-67ae-4029-9975-7cc873b3fe9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ad.plus/adplus-advertising.svg' and @alt = 'adplus-dvertising' and @title = 'Ad.Plus Advertising']</value>
      <webElementGuid>904205ed-29c7-40b4-bc8a-0c25614f31d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
